### ISSUE TITLE
It takes around 1-2 minutes to login.

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#104]
**Describe the Bug**
When you login, it takes 1-2 minutes for the site to redirect to the login page

**Steps to Reproduce**
1. Login from the homepage
2. Wait 1-2 minutes
3. The page loads

**Expected Behavior**
You don't wait 1-2 minutes for the page to load and it just redirects

**Environment**
- OS: MacOS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 84.0.4147.105 (Official Build) (64-bit)

**Additional Information**
Even going to the login page takes a long time to load...

**Comment by advaith1** [comment]
can't reproduce: login is instant for me

**Comment by Cairo2k18** [comment]
Is this main site or lgbt?

**Comment by DuckMasterAl** [comment]
> Is this main site or lgbt?

main site

**Comment by advaith1** [comment]
for me, both are instant but logging in or out in the lgbt site goes to a 404 page such as https://dev-lgbt.discordextremelist.xyz/en-US/fa/webfonts/fa-duotone-900.woff2

**Comment by Cairo2k18** [comment]
> for me, both are instant but logging in or out in the lgbt site goes to a 404 page such as https://dev-lgbt.discordextremelist.xyz/en-US/fa/webfonts/fa-duotone-900.woff2

I thought I fixed this?

**Comment by advaith1** [comment]
you changed the code but didnt do anything, im working on fixing the root cause though

**Comment by advaith1** [comment]
fixed redirection issue 🎉

**Comment by DuckMasterAl** [comment]
Ok time to see and restart my router...

**Comment by DuckMasterAl** [comment]
Login works now soooooo...
