### ISSUE TITLE
Unapproving goes to the home page

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#105]
**Describe the Bug**
Unapproving doesn't stay on the bot, it redirects to the homepage.

**Steps to Reproduce**
1. Unapprove a bot

**Expected Behavior**
You stay on the bot's page or get sent to the approval queue

**Environment**
- OS: MacOS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 84.0.4147.105 (Official Build) (64-bit)

**Comment by Cairo2k18** [comment]
Can repro, had this issue earlier and forgot to fix/make an issue.
