### ISSUE TITLE
Make a character limit

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#106]
**Is your feature request related to a problem? Please describe.**
Yes, there is no character limit on any of the submit bot fields.
**Describe the solution you'd like**
Add a character limit so the stuff shown in the attached image doesn't happen.

**Additional context**
<img width="1437" alt="Screen Shot 2020-08-09 at 10 40 08 PM" src="https://user-images.githubusercontent.com/43557963/89748469-62beb580-da91-11ea-93c7-27ace65ff615.png">
:warning: The video contains lots of moving text - You can view it [here](https://youtu.be/IB-SNFXmCcY)

**Comment by DuckMasterAl** [comment]
This also causes an error when you deny it with a lot of characters 
<img width="1051" alt="Screen Shot 2020-08-09 at 10 47 16 PM" src="https://user-images.githubusercontent.com/43557963/89748706-89c9b700-da92-11ea-97f9-c527b23bd7e2.png">

**Comment by Cairo2k18** [comment]
@advaith1 didn't you already do this?

**Comment by advaith1** [comment]
i dont think so

**Comment by Cairo2k18** [comment]
alright

**Comment by TheMoksej** [comment]
Please add this change faster. People keep doing the same shit over and over again

![image](https://user-images.githubusercontent.com/58531286/92767145-2388ca80-f397-11ea-99a9-813e71b0a65f.png)

**Comment by advaith1** [comment]
@DuckMasterAl @TheMoksej what about these:
- 15 chars for twitter
- 32 chars for prefix
- 75 chars for privacy policy

**Comment by TheMoksej** [comment]
> @DuckMasterAl @TheMoksej what about these:
> 
> * 15 chars for twitter
> * 32 chars for prefix
> * 75 chars for privacy policy

Seems good

**Comment by TheMoksej** [comment]
don't forget about short desc though
