### ISSUE TITLE
Denying a template brings you to a 404

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#109]
**Describe the Bug**
Denying a template brings you to a 404 page with a broken error message

**Steps to Reproduce**
1. Successfully Deny a Template

**Expected Behavior**
You get sent to the homepage

**Environment**
- OS: MacOS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 84.0.4147.105 (Official Build) (64-bit)

**Screenshots**
<img width="333" alt="Screen Shot 2020-08-09 at 11 32 20 PM" src="https://user-images.githubusercontent.com/43557963/89750145-ba145400-da98-11ea-8eb3-facd54878f46.png">

**Comment by advaith1** [comment]
there is no template queue, you can't deny a template

**Comment by DuckMasterAl** [comment]
> there is no template queue, you can't deny a template
> 
> did you mean removing a template?
> 
> 

Yes, sorry.

**Comment by advaith1** [comment]
I thought we supported archiving but apparently we don't, will fix
