### ISSUE TITLE
Users can view archived bots

### ISSUE THREAD

**Issue by Cairo2k18** [discordextremelist/website#116]
Users can view archived bots, also you see the unapproved badge while archived (must fix).

**Comment by advaith1** [comment]
intended

**Comment by Cairo2k18** [comment]
Not intended.

**Comment by advaith1** [comment]
I intentionally changed this after mod feedback, so yes it is intended

**Comment by Cairo2k18** [comment]
> I intentionally changed this after mod feedback, so yes it is intended

Only mods and owner should be able to view.

**Comment by Cairo2k18** [comment]
That was how I had it unless I accidentally removed something.

**Comment by advaith1** [comment]
Nobody could view it before, and mods wanted it to be public to everyone (it is not listed anywhere so people can only access it with the direct URL), and i agree that that is the best solution.

**Comment by Cairo2k18** [comment]
I disagree also I noted other problems in this issue iirc

**Comment by Cairo2k18** [comment]
Either way it's a bug and all users imho shouldn't have access
