### ISSUE TITLE
Improve site performance

### ISSUE THREAD

**Issue by carolinaisslaying** [discordextremelist/website#119]
Do this using mainly frontend adjustments, preferably minimal to no adjustment to the main stylesheet.

**Comment by advaith1** [comment]
We've added `NODE_ENV=production` to improve performance but we should do more

**Comment by Cairo2k18** [comment]
> We've added `NODE_ENV=production` to improve performance but we should do more

Any more ideas?

**Comment by Cairo2k18** [comment]
Some fixes I made;
* ea03fa698ce3445bccb0cea1bb9481b879c49e3b
* ef3d0c74bc0ae10aade33fea7e45c1f3a2e499cf
* 3bc44b63d1497cc152df566b6070eba9dfbecee5
* 48775e77f56039f69be77d8d001f36b52c9b0d06

**Comment by advaith1** [comment]
[reverts: 98686960fc121f3d406253a955bee432ef0bd54a, 6e8fa02e1833e13fcb0e8d90807dc892387ed4f5]

0a408aeb7f6e061c994cf6b11e977a0ef3e876c4, d573ec538caf01f41da3a75a430302c41c5e988e, f34ee554dec610a07cd13bdd14dba545aa5c84d0

**Comment by advaith1** [comment]
lgbt website: f0a79ce9edf45c0979de5678a859eb32467ac64a, 66fb6fac0067ee65ef050a7b53229ede6345c7b0, 7d8c9e32fc95f3efbe16b9156bd377e2aecd4b1b, 5ab8ab924a4018da6c8fb2a91bb357105ada4506

**Comment by Cairo2k18** [comment]
should I merge all non-critical scripts into a file (that are needed for that page, max 2 script reqs probably) and load them using async? @advaith1

**Comment by Cairo2k18** [comment]
4b6f6ff139af71fb950541a39b88fa695346d583

**Comment by Cairo2k18** [comment]
discordextremelist/lgbt-website@e90e0d2444e39c39c1623861bf716a6d025c50ed

**Comment by Cairo2k18** [comment]
bade4929ba011355f57277ebb4f27eb5186c510d

**Comment by carolinaisslaying** [comment]
Being worked on and discussed elsewhere, see #273 #261 for ongoing progress. Further discussion can be held on our Discord server. If you have a specific issue please create a new issue, or ideally comment on #273.
