### ISSUE TITLE
Bring Back DEL Certification

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#129]
**Is your feature request related to a problem? Please describe.**
Yes, discord verification is bad

**Describe the solution you'd like**
Have DEL Certification for bots

**Additional context**
Very cool conversation about verification
<img width="725" alt="Screen Shot 2020-08-25 at 10 58 54 AM" src="https://user-images.githubusercontent.com/43557963/91190877-15159000-e6c2-11ea-9969-66bc24a55a8e.png">

**Comment by advaith1** [comment]
Discord verification and DEL certification aren't related, we removed DEL certification because it's pointless

**Comment by DuckMasterAl** [comment]
> Discord verification and DEL certification aren't related, we removed DEL certification because it's pointless

Cairo said that you guys didn't need del certification because discord was adding their own certification and verified bots get a special badge/check (at least I think they do)

**Comment by advaith1** [comment]
the discord verification badge was removed in del because verification only means that the bot isn't tiny; DEL certification was removed as it's a separate queue and it's pretty pointless as certified bots don't really get anything (also the bot needs to be good to get approved anyway)

**Comment by DuckMasterAl** [comment]
> the discord verification badge was removed in del (early on v5) because verification only means that the bot isn't tiny; DEL certification was removed as it's a separate queue and it's pretty pointless as certified bots don't really get anything (also the bot needs to be good to get approved anyway)

Do you want a list of perks then?

**Comment by Cairo2k18** [comment]
> > the discord verification badge was removed in del (early on v5) because verification only means that the bot isn't tiny; DEL certification was removed as it's a separate queue and it's pretty pointless as certified bots don't really get anything (also the bot needs to be good to get approved anyway)
> 
> Do you want a list of perks then?

No, he just explained why we removed both things.

**Comment by DuckMasterAl** [comment]
@Cairo2k18 can we take del poll on it pls

**Comment by Cairo2k18** [comment]
No

**Comment by DuckMasterAl** [comment]
:c
