### ISSUE TITLE
Do not ask for join server permission when unchecked joining on login

### ISSUE THREAD

**Issue by siddhpant** [discordextremelist/website#136]
Logging in with Discord requires me to give `Join servers for you` permission, which I assume is for making me join DEL server.

But on https://discordextremelist.xyz/en-US/auth/login there's a toggle (in form of a checkbox) which allows me to specify if I want you to make me join the server or not.

If checkbox is not ticked, it is unnecessary to ask for the permission. Unnecessary permissions are bad.

**Comment by Cairo2k18** [comment]
It is necessary for adding bots.

**Comment by advaith1** [comment]
To give more details: even if you do not select the option to be added when you log in to the site (which will be off by default in the upcoming update), users are added to the server when they submit a bot, to make it easy for us to work with the bot dev to resolve any issues we find while testing it. While the current system does have the unfortunate effect of granting a permission that may not be needed, it results in less friction for users. You can remove the guilds.join scope when logging in if you want, it won't break anything except possibly adding bots.

**Comment by siddhpant** [comment]
Users can be told to join manually (like every other list) if they decline to give the permission.

**Comment by Cairo2k18** [comment]
> Users can be told to join manually (like every other list) if they decline to give the permission.

Fair point, users are told that they will be joined, as advaith said the button is off by default as of the next version, if people want to remove the scope they can, but I feel like disabling it when that's unchecked will cause more issues than needed. I understand what you mean though.
