### ISSUE TITLE
Remove underline under tag icon.

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#140]
**Is your feature request related to a problem? Please describe.**
Yes, the underline under the tag icon is ugly.

**Describe the solution you'd like**
Make it so that the tag icon doesn't have an underline while the rest of the text does.

**Describe alternatives you've considered**
Make it all not underlined.

**Additional context**
<img width="89" alt="Screen Shot 2020-09-16 at 10 53 45 AM" src="https://user-images.githubusercontent.com/43557963/93354546-1b9faf00-f80b-11ea-8cbe-7b96767cb208.png">

**Comment by advaith1** [comment]
bot tags now become darker on hover instead of underlined 🎉 
this has been planned since 5.3 release but i never got around to it before lol
