### ISSUE TITLE
Going to a page that should 404 takes you to the homepage

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#141]
**Describe the Bug**

Going to a website like https://discordextremelist.xyz/thisisnotarealpage takes you to the homepage.
**Steps to Reproduce**

1. Go to a page that doesn't exist on del (without language subpage)
2. Welcome to the homepage

**Expected Behavior**

You go to the 404 page

**Environment**

- OS: MacOS Catalina 10.15.6
- Browser: Chrome
- Version: 85.0.4183.102 (64-bit)

**Comment by advaith1** [comment]
known issue, this has always annoyed me but Cairo says that it's not possible to fix without re-doing i18n stuff :(

**Comment by Cairo2k18** [comment]
> known issue, this has always annoyed me but Cairo says that it's not possible to fix without re-doing i18n stuff :(

ik I want to fix it too but it's too difficult

**Comment by DuckMasterAl** [comment]
oof

**Comment by TheMoksej** [comment]
bruh

**Comment by Cairo2k18** [comment]
This will not be changed anywhere in the near future, closing issue until relevant again.

**Comment by advaith1** [comment]
it's a big issue, it should not be closed

**Comment by advaith1** [comment]
fixed :tada:
