### ISSUE TITLE
Icons and fonts don't load correctly on Firefox

### ISSUE THREAD

**Issue by Cairo2k18** [discordextremelist/website#147]
**Describe the Bug**
Icons and fonts don't load correctly on Firefox.

**Steps to Reproduce**

Ensure environment is the same and go onto the website, it will be immediately noticeable. This is not an issue on the Nightly/Dev builds on Firefox.

**Expected Behavior**

The icons and fonts should load normally as they do on other browsers such as Chrome and Edge.

**Screenshots**

![image](https://user-images.githubusercontent.com/38713645/94327664-9e411f00-0000-11eb-876d-3e8739a18c81.png)

**Environment**

- OS: Windows 10
- Browser: Firefox
- Version: 81.0 (64bit)h

**Comment by advaith1** [comment]
issue with old firefox versions, not our problem

**Comment by Cairo2k18** [comment]
> issue with old firefox versions, not our problem

*the latest stable version

**Comment by advaith1** [comment]
latest stable is old

**Comment by Cairo2k18** [comment]
> latest stable is old

stable is stable, doesn't matter.

**Comment by Cairo2k18** [comment]
Is this patched @advaith1?

**Comment by Cairo2k18** [comment]
Nevermind I see #148

**Comment by advaith1** [comment]
@Cairo2k18 uh.. I thought you did it?

**Comment by Cairo2k18** [comment]
> @Cairo2k18 uh.. I thought you did it?

I didn't test it.
