### ISSUE TITLE
Bot analytics

### ISSUE THREAD

**Issue by carolinaisslaying** [discordextremelist/website#160]
Gives developers in analytics for their bots and allow logged in users to opt-out, etc.

We could include some of the following:

- Pageviews with options to change views between days, weeks and months
- Pageviews with geo data pie chart
- Invite button count with options to change views between days, weeks and months
- Invite button with geo data pie chart
- Record bot guilds using the API but also store it allowing us to create guild count graphs
- Upvotes/downvotes count with options to change views between days, weeks and months
- Upvotes/downvotes with geo data pie chart
- Page referrer

**Comment by Cairo2k18** [comment]
tl;dr analytics because we can't have less features than top.gg

**Comment by TheMoksej** [comment]
sounds cool
