### ISSUE TITLE
bots aren't getting kicked

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/website#164]
Not sure if d.py bot does kicking or d.js, but bots aren't being kicked when approved/declined/unapproved.

**Comment by TheMoksej** [comment]
this seems to have been fixed, but not 100% sure yet.

**Comment by advaith1** [comment]
🤔 code hasn't been changed, I'll look into this tomorrow/this weekend tho

**Comment by advaith1** [comment]
can't reproduce

![ss](https://advaith.is-in-hyper.space/042cc976c4.png)

**Comment by Cairo2k18** [comment]
> seems like it fixed by itself, but not 100% sure yet.

@advaith1 I'm assuming this is resolved.
