### ISSUE TITLE
cant access invite queue

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/website#165]
Invite queue keeps loading and eventually 524s

**Comment by Cairo2k18** [comment]
I'll fix it when I get home if advaith can't.

**Comment by TheMoksej** [comment]
> I'll fix it when I get home if advaith can't.

he said it works in dev :/

**Comment by Cairo2k18** [comment]
@IceeMC can you check logs while trying to access it please?

**Comment by Cairo2k18** [comment]
ffs fine then

**Comment by Cairo2k18** [comment]
I can't seem to find the issue

**Comment by TheMoksej** [comment]
Ok sweet, Ice fixed it

**Comment by advaith1** [comment]
no, I fixed it yesterday

**Comment by TheMoksej** [comment]
> no, I fixed it yesterday

Okay you and Ice did it. Good job
