### ISSUE TITLE
Add staff panel dropdown to site header

### ISSUE THREAD

**Issue by Techy** [discordextremelist/website#167]
**Is your feature request related to a problem? Please describe.**
I’m suggesting this so staff can easily navigate to the staff panel in 1 click. Currently, we need to click our username then click staff panel. 

**Describe the solution you'd like**
Add a staff panel dropdown in the website header.

**Additional context**
![](https://media.discordapp.net/attachments/539313586611290114/764616564984250371/unknown.png)

**Comment by Cairo2k18** [comment]
@advaith1 
option a)
![image](https://user-images.githubusercontent.com/38713645/96708100-3dd1b180-13f5-11eb-832d-3ab97a9af717.png)
option b)
![image](https://user-images.githubusercontent.com/38713645/96708162-50e48180-13f5-11eb-88b7-b15f7fceab2f.png)
option c)
![image](https://user-images.githubusercontent.com/38713645/96708221-678ad880-13f5-11eb-9755-6215b6adbe50.png)

option b and c might cause issues on smaller screens, c definitely will but idk we could do both and use css to remove text from them if screen size is too small but, then mobile nav can just display text regardless (for obvious reasons).

**Comment by advaith1** [comment]
yeah we can use css to switch depending on screen size
