### ISSUE TITLE
API Docs are outdated with Authorization Requirements

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#178]
**Describe the Bug**

The API Documentary says that all get functions need API keys when they don't!
**Steps to Reproduce**

1. Go to [the docs](https://discordextremelist.xyz/en-US/docs#api-routes)

**Expected Behavior**

The API Docs don't have a :lock: next to all the `get` routes

**Environment**

N/A

**Comment by advaith1** [comment]
already fixed, just not deployed yet
