### ISSUE TITLE
Fix blog and make more posts 

### ISSUE THREAD

**Issue by darling-fire** [discordextremelist/website#181]
**Describe the Bug**

 Blog doesn’t work 
**Steps to Reproduce**

1. Visit the blog 
2. It doesn’t work
3. Be more active on the blog and make posts more often

**Expected Behavior**

Blog should work
**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by advaith1** [comment]
The blog works fine for me, are you getting an error?

**Comment by darling-fire** [comment]
you guys should make more posts

**Comment by darling-fire** [comment]
I am getting nginx error

**Comment by advaith1** [comment]
can you screenshot it?

**Comment by darling-fire** [comment]
on my school ipad  they locked it I can’t take screenshot

**Comment by darling-fire** [comment]
can you make more posts on the blog though?

**Comment by advaith1** [comment]
unless someone else can reproduce, assuming this is a troll and closing

**Comment by darling-fire** [comment]
it just says ngix error in plain text

**Comment by darling-fire** [comment]
I am not trolling it is a real error
