### ISSUE TITLE
Feature Suggestions to improve Discord Extreme List

### ISSUE THREAD

**Issue by alfredsaveron** [discordextremelist/website#183]
**Feature Suggestions to improve Discord Extreme List**

1 • In the servers list, there should be a field that **shows the number of members and emojis** on the server. In this way, Discord Extreme List users can access more detailed information about the server.

2 • There should be a "**Top Rated**" page that lists the top rated bots, or bots on the most servers. In this way, Discord Extreme List users can quickly see recommended bots. ( e.g discordextremelist.xyz/top )

3 • For bots listed on the Discord Extreme List, **more tag possibilities should be provided**. (eg League of Legends, New Bots, Minecraft, Apex Legends, DOTA 2 and more ..)

Thanks, stay safe - stay home. :octocat:

**Comment by advaith1** [comment]
> shows the number of members

this is planned but is pending on #176

> and emojis 

we can't access this

> There should be a "Top Rated" page that lists the top rated bots, or bots on the most servers

yeah we should add more sorting options, server count would be useful imo but not sure about votes (cc @Cairo2k18)

> more tag possibilities should be provided

i suppose we could add new tags if we have enough bots that fit them

**Comment by Cairo2k18** [comment]
> > shows the number of members
> 
> this is planned but is pending on #176
> 
> > and emojis
> 
> we can't access this
> 
> > There should be a "Top Rated" page that lists the top rated bots, or bots on the most servers
> 
> yeah we should add more sorting options, server count would be useful imo but not sure about votes (cc @Cairo2k18)
> 
> > more tag possibilities should be provided
> 
> i suppose we could add new tags if we have enough bots that fit them

for the "Top Rated" one, yeah I'd rather not because of the whole 'unbiased' thing, however I would be fine to explore new tag options - however this could be seen as an extension of #98.
