### ISSUE TITLE
Premium servers

### ISSUE THREAD

**Issue by MiataBoy** [discordextremelist/website#185]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add premium servers the same way that you have premium bots.

**Comment by Cairo2k18** [comment]
What features would be added for premium servers?

**Comment by BluewyDev** [comment]
- vanity url
- the premium badge
- use JS on Server pages

More features may follow up later

**Comment by Cairo2k18** [comment]
> * vanity url
> * the premium badge
> * use JS on Server pages
> 
> More features may follow up later

idk about JS, @advaith1 thoughts?

**Comment by advaith1** [comment]
i think its a good idea, should also add iframes and css

**Comment by Cairo2k18** [comment]
> i think its a good idea, should also add iframes and css

Agreed, exclude JS though, right?

**Comment by advaith1** [comment]
why?

**Comment by Cairo2k18** [comment]
> why?

idk, was more asking, thought you would think it should be excluded..?
