### ISSUE TITLE
Recommend PreMiD presence

### ISSUE THREAD

**Issue by Cairo2k18** [discordextremelist/website#186]
Detect if users are using PreMiD and recommend that they install the official Discord Extreme List PreMiD extension.

**Comment by advaith1** [comment]
is it possible for us to detect that?

**Comment by Cairo2k18** [comment]
> is it possible for us to detect that?

possibly, I will look into it after other issues have been done.

**Comment by Cairo2k18** [comment]
actually ik how to do this an easier way
