### ISSUE TITLE
Invalid server & template alerts for moderators

### ISSUE THREAD

**Issue by Techy** [discordextremelist/website#187]
**Is your feature request related to a problem? Please describe.**
I’ve noticed that there are quite a few servers and templates with invalid links.

**Describe the solution you'd like**
It would be useful if servers & templates with invalid links could be sent to a channel for further moderator review. This would help clean up the site and ensure that all servers/templates are able to be joined/used by users.

**Comment by advaith1** [comment]
already planned, pending on #176
