### ISSUE TITLE
Add bots to discord server toggle

### ISSUE THREAD

**Issue by BluewyDev** [discordextremelist/website#188]
**Is your feature request related to a problem? Please describe.**
Some bot devs don't want their bot in the discord server.

**Describe the solution you'd like**
basically have a toggle for adding the bot to the discord server (at approval) or not in staff management

**Describe alternatives you've considered**

**Additional context**
CC Moksej

**Comment by advaith1** [comment]
> Some bot devs don't want their bot in the discord server.

who? and why? I'm not sure if this is worth adding

**Comment by TheMoksej** [comment]
Yes, cc me. I'll explain further in the morning.

**Comment by TheMoksej** [comment]
> > Some bot devs don't want their bot in the discord server.
> 
> who? and why? I'm not sure if this is worth adding

You'll see in the future, some of them don't like that

**Comment by IceeMC** [comment]
que?

**Comment by Cairo2k18** [comment]
> > > Some bot devs don't want their bot in the discord server.
> > 
> > 
> > who? and why? I'm not sure if this is worth adding
> 
> You'll see in the future (once we'll get bigger), some of them don't like that

I haven't seen anyone say they didn't want their bot in the server yet, if they have a problem they can message a staff member - no point in adding a feature that <0.00000001% of people will use.
