### ISSUE TITLE
copy bot owner user id

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/website#189]
Instead of having to open owner's account from the bot's page and press the "Copy User ID" button, add "Copy Owner User ID" button on the bot's page itself. _yes I'm lazy ok_

Example: 
![image](https://user-images.githubusercontent.com/58531286/103282877-5e128380-49d7-11eb-9523-68e8a6244442.png)

**Comment by advaith1** [comment]
what's the use case for this?

**Comment by TheMoksej** [comment]
> what's the use case for this?

copy user id of the owner _I tend to check if owner is in the server before I test their bot so I'd know if I need to continue the testing after I find a single issue or not_
