### ISSUE TITLE
Slash Command tag page isn't showing all applicable bots

### ISSUE THREAD

**Issue by advaith1** [discordextremelist/website#191]

**Comment by Cairo2k18** [comment]
Is this still happening?

**Comment by advaith1** [comment]
yes

**Comment by Cairo2k18** [comment]
> yes

any idea as to what is causing this yet or is it still a confusing problem?

**Comment by advaith1** [comment]
no idea

**Comment by advaith1** [comment]
deleted and re-added yesno to the site, and i haven't heard any other reports, so i suppose this is fixed? 🤷🏾‍♂️
