### ISSUE TITLE
Crowdin string updates

### ISSUE THREAD

**Issue by Carolina2k22** [discordextremelist/website#197]
Inspiration/example: https://github.com/PreMiD/API/blob/main/src/util/crowdinManager.ts

**Comment by Andre601** [comment]
This is about what exactly now?
Using a different way of uploading and retrieving translations? Perhaps the [Crowdin GitHub-Action](https://github.com/crowdin/github-action) is something you would want to use?

**Comment by comradekingu** [comment]
Crowdin makes the least amount of sense for copylefted libre software.
Leaving this here https://docs.weblate.org/en/latest/admin/continuous.html?highlight=github#automatically-receiving-changes-from-github :)
