### ISSUE TITLE
Changing Client ID

### ISSUE THREAD

**Issue by FlitzDev** [discordextremelist/website#204]
**Is your feature request related to a problem? Please describe.**
Yes, i moved my bot to a new bot account but i am unable to change the Client ID to the new one.

**Describe the solution you'd like**
I would like for it to be possible to change the Client ID of your bot, perhaps with a confirmation message if needed.

**Describe alternatives you've considered**
I have considered alternative solutions like asking someone to change it for me in the DataBase, but i feel like this would make it much easier.

**Comment by advaith1** [comment]
Since the bots are stored by id, pretty sure we cannot change a bot's id, we would have to delete and re-create it, @Cairo2k18 can confirm

and anyway I don't think this is really something we would want to do anyway; you can just submit the new bot separately

**Comment by FlitzDev** [comment]
Fair enough. Just figured if this were to be possible it would ease the process of submitting the new account (but same bot). Thanks anyway

**Comment by Cairo2k18** [comment]
> Since the bots are stored by id, pretty sure we cannot change a bot's id, we would have to delete and re-create it, @Cairo2k18 can confirm
> 
> and anyway I don't think this is really something we would want to do anyway; you can just submit the new bot separately

Yeah I'd have to agree. Just resubmit and copy your description, etc.
