### ISSUE TITLE
Editors bug

### ISSUE THREAD

**Issue by BluewyWolff** [discordextremelist/website#205]
**Describe the Bug**
When submitting a bot, and it's not been approved yet it shows the first editor, and the second editor is indicated with a mere `&nbs`. A great example is on https://discordextremelist.xyz/en-US/bots/843252491473649665 and here's an image:

**Steps to Reproduce**

1. Uh, submit a bot with editors i guess?
2.
3.

**Expected Behavior**
Was supposed to be showing all the editors normally

**Screenshots**

![image](https://user-images.githubusercontent.com/34064010/118401813-7114b000-b667-11eb-90cb-4c6ab5ed39fd.png)

**Environment**

- OS: Windows 10
- Browser: Edge
- Version: 90.0.818.56

**Additional context**

**Comment by Cairo2k18** [comment]
Quick fix - get the user to login to the DEL site
What I'll do - make it fetch info from Discord (and cache) when not found on DEL

**Comment by Carolina2k22** [comment]
Fixed in v5.4.22
