### ISSUE TITLE
LGBTQ servers queue bypass

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/website#210]
**Describe the Bug**
All LGBTQ servers are supposed to be manually approved by the moderator, however, you can easily bypass it.

**Steps to Reproduce**
1. Submit a server with LGBTQ Community tag
2. Edit the server and select more tags to be added
3. Hit save

**Expected Behavior**
The server stays unapproved until the moderator manually approves it

**Screenshots**

https://user-images.githubusercontent.com/58531286/124476422-12d09780-dda3-11eb-9713-d1a7a3804e90.mp4

**Environment**
This is unnecessary.

**Additional context**
Go fix, kthx

**Comment by Carolina2k22** [comment]
Fixed
