### ISSUE TITLE
LGBTQ tag on templates/bots

### ISSUE THREAD

**Issue by FlitzDev** [discordextremelist/website#212]
**Is your feature request related to a problem? Please describe.**
Not necessarily, tho it can be a buzzkill not having those tags for bots/templates while potentially having that as it's main point

**Describe the solution you'd like**
Simply add the LGBTQ tag as a tag for bots and templates as well, possibly list these on the .gay website as well, but is not fully necessary.

**Describe alternatives you've considered**
There's no alternative to this.

**Additional context**
The only additional context is that servers are an example of this.

**Comment by Cairo2k18** [comment]
Yeah.. no, the .gay site is meant to promote LGBTQ+ Communities.
