### ISSUE TITLE
"Basic View" Mode (But A Bit Overcomplicated)

### ISSUE THREAD

**Issue by GodTitan13** [discordextremelist/website#216]
Add a "Basic View" (sorta like what Gmail has) that simplifies the website, reduces colors, removed complicated graphics, displays less unneeded info, etc. 

If possible, a popup should appear when slow loading of the page from a user is detected telling them that they can switch to the Basic View for faster loading speed. This popup should have an option to click "Do Not Show Again" & "Proceed".

When basic view is enabled, loading the website should bring a popup that says they had last used basic view and if they would like to continue with basic view or regular view. There should also be a setting that sets the default view and that should be mentioned there as a way to stop this popup from showing up. There should also be another setting mentioned that can stop the popup which would be a "Load Most Recent View Mode"

**Comment by advaith1** [comment]
no
