### ISSUE TITLE
Textual Improvement For Other 'Server Listing' Guidelines

### ISSUE THREAD

**Issue by GodTitan13** [discordextremelist/website#218]
Under "Server Guidelines" there is "Listing Guidelines" and under that is "Other Guidelines" and under this is the following text:

Your server must follow the Discord Terms of Service and actively enforce it.

This text should be updated to say:

Your server and staff must follow the Discord Terms Of Service & Community Guidelines.

**Comment by Cairo2k18** [comment]
Complying with ToS implies following community guidelines, and server implies members and thus staff as well.
