### ISSUE TITLE
Horizontal Display Of Reccomendations On The Home Page

### ISSUE THREAD

**Issue by GodTitan13** [discordextremelist/website#220]
There should be an option that we can enable to make it so that the reccomendations on the home page display horizontally rather then vertically. 

Part of this means that the amount of content should be increased (only for the users who enable this option preferably since vertical display users will start wanting to switch to horizontal display and that's not the point of this option) to give reasoning for this option other then the user's preference.

**Comment by Cairo2k18** [comment]
> There should be an option that we can enable to make it so that the reccomendations on the home page display horizontally rather then vertically.
> 
> Part of this means that the amount of content should be increased (only for the users who enable this option preferably since vertical display users will start wanting to switch to horizontal display and that's not the point of this option) to give reasoning for this option other then the user's preference.

could you please explain further? I'm not quite sure I understand
