### ISSUE TITLE
Non-slash application commands are displayed under the "Slash Commands" header

### ISSUE THREAD

**Issue by shayypy** [discordextremelist/website#226]
**Describe the Bug**

User and message application commands are shown under the "Slash Commands" header on bot pages.

**Steps to Reproduce**

1. Visit a bot page with non-slash application commands ([example](https://discordextremelist.xyz/en-US/bots/bearger), [example](https://discordextremelist.xyz/en-US/bots/tabletophat)) and scroll down to "Slash Commands"
2. All types of application commands are displayed

**Expected Behavior**

Only slash commands should be displayed. I would recommend making two more sections for "User Commands" and "Message Commands"

**Screenshots**

![image](https://user-images.githubusercontent.com/43248357/131265519-03924221-a6ed-4253-884b-dfc6b1dff676.png)

**Environment**

I don't think this part of the form is relevant to this specific issue. Will fill out if needed lol

**Additional context**

**Comment by advaith1** [comment]
i think i noticed this before ctx menus released but never fixed it lol

we'll probably just filter non-slash commands out

**Comment by Carolina2k22** [comment]
Already fixed in bc55a5ee1b8720e4b8874b8ce515588dc844e0a0
