### ISSUE TITLE
Prioritise custom css classes over the sites default

### ISSUE THREAD

**Issue by Antouto** [discordextremelist/website#243]
**Is your feature request related to a problem? Please describe.**
In the style tag things like `table`, `button` or `div` will be overridden by some default css while custom classes are prioritised over the default css. 

**Describe the solution you'd like**
I'd like not only classes but everything in the style tag prioritised over dellys default css

**Describe alternatives you've considered**
Changing my `table`, `button`, `div` etc. to classes so they are prioritised

**Comment by Antouto** [comment]
I just noticed I'm probably supposed to be using `!important`?

**Comment by ConnorDoesDev** [comment]
Go ahead.
