### ISSUE TITLE
Missing Patreon icon in footer

### ISSUE THREAD

**Issue by marshallovski** [discordextremelist/website#250]
**Describe the Bug**

Missing Patreon icon in footer

**Steps to Reproduce**

1. Check the footer
PROFIT!

**Expected Behavior**

Normal Patreon icon
**Screenshots**

![image](https://user-images.githubusercontent.com/68496774/167146220-0254ca8c-d7e6-4365-a6b7-82b711b23992.png)
**Environment**

- OS: Windows 10
- Browser: Firefox
- Version: 99.0.1 (64-bit)
  

**Additional context**

**Comment by Carolina2k22** [comment]
@marshallovski thank you for reporting this

**Comment by Carolina2k22** [comment]
Cannot repro on my system
> OS: Windows 11 
> Browser: Microsoft Edge
> Version: 101.0.1210.32 (64-bit)
Likely a Firefox issue as I recall seeing this once or twice a couple years go on other sites when using Firefox. Will look to making a specific patch for it ASAP.

**Comment by ConnorDoesDev** [comment]
I also cannot reproduce this on my system

> OS: Windows 10
> Browser: Google Chrome
> Version: 19043.1645 (64-bit)

**Comment by Carolina2k22** [comment]
Yep, I'll still look into it because I'm 100% sure it's affecting a lot of FF versions for some reason, thought it was fixed but nevermind

**Comment by carolinaisslaying** [comment]
Cannot reproduce on newer Firefox versions on macOS.
<img width="729" alt="image" src="https://github.com/discordextremelist/website/assets/38713645/2d9f4cbc-dcbb-4214-b7c4-329635201093">
<img width="493" alt="image" src="https://github.com/discordextremelist/website/assets/38713645/2b19d935-24af-40da-8231-adad450181b3">
