### ISSUE TITLE
Move to golang

### ISSUE THREAD

**Issue by carolinaisslaying** [discordextremelist/website#251]

**Comment by Carolina2k22** [comment]
> the complete codebase?

was a thought me and ice were discussing, and hypothetically yeah

**Comment by Carolina2k22** [comment]
probably not anytime soon

**Comment by TheAlienKnight** [comment]
Reinventing the wheel is always something to avoid, so I'll put my 2 cents in the bucket. The current codebase in all honesty- isn't too bad, it just needs to be segmented/divided up for readability. There's also some general things that can improve the speed, etc of it, but those become much clearer when things aren't all bunched up together. A full rewrite would take a lot considering you'd need to obviously redo the entire backend. For the frontend, there are some golang alternatives to ejs, like [Fiber](https://docs.gofiber.io/) that are made to be easy to switch to. 

It's also worth noting that while GoLang is good at performance, it doesn't have much [adoption](https://www.digitalocean.com/currents/june-2022#emergingtrends) as of yet.
