### ISSUE TITLE
cant install on my vps

### ISSUE THREAD

**Issue by builtbyjonas** [discordextremelist/website#254]
**Describe the Bug**
When i try to do ``npm i`` then it gives me a error.

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**
 after i run ``npm i`` it gives me a error.

**Screenshots**
![Screenshot (235)](https://user-images.githubusercontent.com/81481526/174434320-759d3560-039b-4e1c-9177-2d86ca8d5113.png)
![Screenshot (234)](https://user-images.githubusercontent.com/81481526/174434326-4d3f8847-1a8a-4d10-895c-14a17249cb80.png)

**Environment**

- OS: Linux, Debian 10
- Browser: 
- Version:
  

**Additional context**

**Comment by ConnorDoesDev** [comment]
we don't provide support for self-hosting DEL.
