### ISSUE TITLE
Snake Improvements

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#27]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
A leaderboard for all the snake scores
**Describe alternatives you've considered**
Adding a leaderboard to the snake game page and get a place number on your profile of your ranking
**Additional context**
Example image attached for what the profile thing could look like.
<img width="625" alt="Screen Shot 2020-05-29 at 10 24 58 AM" src="https://user-images.githubusercontent.com/43557963/83270635-c0cc4400-a196-11ea-833c-0b801844b500.png">

**Comment by DuckMasterAl** [comment]
Also, adding auto-refreshing after every game to refresh your High Score on the page since currently, you need to refresh the page instead of it auto-updating.

**Comment by Cairo2k18** [comment]
I won't show snake place on profile, but there will be a leaderboard

**Comment by DuckMasterAl** [comment]
@Cairo2k18 just an idea maybe move the logout button to the bottom, instead of the leaderboard at the bottom.
<img width="257" alt="Screen Shot 2020-07-16 at 9 36 22 AM" src="https://user-images.githubusercontent.com/43557963/87677654-05f90500-c748-11ea-8822-ae70d83c0f98.png">
