### ISSUE TITLE
Docs take you to an unknown page

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#28]
**Describe the Bug**

Trying to the Docs' Search link results in a 404
**Steps to Reproduce**

1. Open the [docs](https://docs.discordextremelist.xyz/)
2. Click Search in the header
3. Look at your 404 and play the snake game

**Expected Behavior**

You get taken to the search page

**Screenshots**

<img width="1440" alt="Screen Shot 2020-05-29 at 2 44 27 PM" src="https://user-images.githubusercontent.com/43557963/83294239-fdaa3200-a1ba-11ea-9927-5e00b69ee5a3.png">

**Environment**

- OS:  MacOS Catalina 10.15.4
- Browser:  Chrome
- Version:   83.0.4103.61 (64-bit)

**Comment by advaith1** [comment]
@Cairo2k18 there shouldnt be a search link there at all

**Comment by DuckMasterAl** [comment]
Maybe just replace it with servers?

**Comment by advaith1** [comment]
well this site is gonna be killed on v5 release anyway so ¯\_(ツ)_/¯

**Comment by DuckMasterAl** [comment]
Yea true we need @Cairo2k18 to work on that instead of this so I'm closing the issue.
