### ISSUE TITLE
Making sure you don't lose information

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#29]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I hit ctrl + r and lose my work.
**Describe the solution you'd like**
Make it so when you do ctrl + r it asks "Are you sure you want to leave this page?"
**Describe alternatives you've considered**
Auto-Saving Features

**Comment by DuckMasterAl** [comment]
Also, this suggestion is brought to you by @Cairo2k18!
<img width="329" alt="Cairo Raging about Losing Progress" src="https://user-images.githubusercontent.com/43557963/83317428-901df600-a1fa-11ea-8091-f8108811bbe1.png">

**Comment by Cairo2k18** [comment]
Good suggestion but browsers will automatically do this on pages when forms have been filled out (such as bot add, etc.) so it would really only be useful for me, which I could probably just use an extension to do.

**Comment by DuckMasterAl** [comment]
Well, it doesn't on Chrome, and according to usefyi.com "More than 310 million people were using Chrome as their primary browser."

**Comment by Cairo2k18** [comment]
> Well, it doesn't on Chrome, and according to usefyi.com "More than 310 million people [are] using Chrome as their primary browser."

It should at least save it, I can't test on chrome right now though. @advaith1 might be able to help with this.

**Comment by advaith1** [comment]
Added a warning when reloading/navigating away from edit and submit pages

**Comment by DuckMasterAl** [comment]
@advaith1 Doesn't happen when you edit your profile and change your global css in preferences.

**Comment by Cairo2k18** [comment]
I'll look at what he did and try implement it on those pages.

**Comment by Cairo2k18** [comment]
Done

**Comment by DuckMasterAl** [comment]
Just saying it asks when you hit save and if you don't make any changes :p

**Comment by advaith1** [comment]
should be fixed, @DuckMasterAl pls confirm (don't wanna have to keep closing and re-opening this issue lol)

**Comment by DuckMasterAl** [comment]
@advaith1 Not on Chrome at least >.<
Here's a cool video showing the error message: https://youtu.be/zaspTWswlQw

**Comment by advaith1** [comment]
That's intended, it should show the warning as long as you aren't actually saving it (clicking menu items does not save, only clicking the green save button saves)

**Comment by DuckMasterAl** [comment]
> Just saying it asks when you hit save and if you don't make any changes :p
I thought you were talking about this comment I made @advaith1 other than that it works as intended. I'll reference the other thing as a separate feature request.

**Comment by advaith1** [comment]
I think i didn't read all of it; i just fixed it asking on save, but it would be more work to check if any changes have been made

**Comment by DuckMasterAl** [comment]
Ok, I opened #34 for the check if changes are made part.
