### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by SplitXPlayZ** [discordextremelist/website#35]
Typo at the description, (Not that big problem)
![index](https://user-images.githubusercontent.com/42723508/83945370-7d16b180-a80a-11ea-95ae-3339754275c3.png)

**Comment by Cairo2k18** [comment]
I'll be redoing this section at some point over the next couple of weeks, thanks for pointing this out though I didn't even realise lol

**Comment by Cairo2k18** [comment]
fixed in [this](https://github.com/discordextremelist/website/commit/97fe5854102ce1232350ce02f83ebdbf7c67793e) commit
