### ISSUE TITLE
Use typescript instead of normal node js

### ISSUE THREAD

**Issue by Cairo2k18** [discordextremelist/website#36]

**Comment by advaith1** [comment]
yes pls

**Comment by Yomanz** [comment]
cant believe its not already

**Comment by IceeMC** [comment]
Should have been in TypeScript since the beginning.

**Comment by Cairo2k18** [comment]
> Should have been in TypeScript since the beginning.

I mean you did work on it since the beginning with me anyway sooo :lul:

**Comment by Cairo2k18** [comment]
Done
