### ISSUE TITLE
The status page uses white text on a white box

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#37]
**Describe the Bug**

The [uptime status page](https://status.discordextremelist.xyz/uptime) uses white text on a white box.
**Steps to Reproduce**

1. Go to the [Uptime Status Page](https://status.discordextremelist.xyz/uptime)
2. Click on the "Website" dropbox
3. Notice that all the text is white on a white dropdown box

**Expected Behavior**

The text/box is a darker color so you can see the options
**Screenshots**

https://file.coffee/u/yCfsUBGBla.png
**Environment**

- OS: MacOS Catalina 10.15.4
- Browser: Chrome
- Version: 83.0.4103.61 (64-bit)
  

**Additional context**

Just reposting [this bug](https://ptb.discordapp.com/channels/568567800910839811/568591098310688769/705506403984343121) found by Anish

**Comment by Cairo2k18** [comment]
Not really a priority, have kinda tried to fix it but it didn't work

**Comment by DuckMasterAl** [comment]
@Cairo2k18 does that mean it's now a feature?

**Comment by Cairo2k18** [comment]
> @Cairo2k18 does that mean it's now a feature?

yes

**Comment by advaith1** [comment]
fixed! @DuckMasterAl thanks for reporting this "feature" :)

![ss](https://advaith.is-in-hyper.space/448f24d6a7.png)
