### ISSUE TITLE
Add bots/servers that aren’t yours to the site.

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#40]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
A way to add bots/servers to the site with a different owner. For example if I don’t own a bot but @dellybot does I can make it so that when @dellybot makes an account with del they’ll have the bot under their profile.
**Describe alternatives you've considered**
Just letting staff add popular bots and a “I’m the owner” button.
**Additional context**

**Comment by Cairo2k18** [comment]
Why not just get them to add it themselves?

**Comment by DuckMasterAl** [comment]
@Cairo2k18 because what if the bot owner is someone important like @octocat and they don't know about del?

**Comment by Cairo2k18** [comment]
> @Cairo2k18 because what if the bot owner is someone important like @octocat and they don't know about del?

Then letting someone else add it is somewhat a security issue?

**Comment by DuckMasterAl** [comment]
> > @Cairo2k18 because what if the bot owner is someone important like @octocat and they don't know about del?
> 
> 
> 
> Then letting someone else add it is somewhat a security issue?

True which is why I said probably staff should be the only ones allowed to do it

**Comment by Cairo2k18** [comment]
> > > @Cairo2k18 because what if the bot owner is someone important like @octocat and they don't know about del?
> > 
> > 
> > Then letting someone else add it is somewhat a security issue?
> 
> True which is why I said probably staff should be the only ones allowed to do it. Maybe not though...

I mean I can always just add it like normal and do a db request to change the owner to a diff id /shrug

**Comment by DuckMasterAl** [comment]
Yea true
