### ISSUE TITLE
Votes title bug

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [discordextremelist/website#42]
**Describe the Bug**
When you hover over the number of "votes" a bot has there is a random `</span>` in the name.

**Steps to Reproduce**
Go to a bot's page and hover over the "votes" number.

**Expected Behavior**
To just show "Votes" instead of "`Votes </span>`"

**Screenshots**
![img](https://i.imgur.com/vrzi6Iz.gif)

**Environment**
- OS: Windows 10
- Browser: Opera
- Version: 68.0.3618.191 (64-bit) 

**Additional context**
N/A

**Comment by advaith1** [comment]
fixed
