### ISSUE TITLE
Empty Editors Tab

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#43]
**Describe the Bug**

The "Editors" option is blank if there are no editors.
**Steps to Reproduce**

Very Live Example: https://discordextremelist.xyz/en-US/bots/478370481926438932

**Expected Behavior**

The box either doesn't appear or says "None"
**Screenshots**

<img width="298" alt="This doesn't help does it..." src="https://user-images.githubusercontent.com/43557963/86041918-6da71480-ba14-11ea-8bf1-cfcf2454c442.png">

**Environment**

- OS: MacOS Catalina 10.15.4
- Browser: Chrome
- Version: 83.0.4103.61 (64-bit)

**Comment by Cairo2k18** [comment]
Fixed
