### ISSUE TITLE
Code blocks hurt my eyes

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#44]
**Is your feature request related to a problem? Please describe.**
This looks so bad...
**Describe the solution you'd like**
Maybe have the background be grey and the text red/white (also if you're really cool add rounded edges)
**Describe alternatives you've considered**
Giving the blocks a different background color (not white)

**Additional context**
<img width="1337" alt="rip eyes" src="https://user-images.githubusercontent.com/43557963/86043906-56b5f180-ba17-11ea-9fdc-c01c5d6ee870.png">

**Comment by Cairo2k18** [comment]
Fixed
