### ISSUE TITLE
Remove offline bots from the home page

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#45]
**Is your feature request related to a problem? Please describe.**
It's annoying when a bot's offline and it's on the home page.
**Describe the solution you'd like**
Make it so that offline bots are not on the home page.
**Describe alternatives you've considered**
Make a note for bots on the homepage that say "I'm offline" if they're offline.

**Comment by Cairo2k18** [comment]
I feel like this would benefit the list BUT could cause some issues at the same time, I have noticed a couple perfectly fine and working bots in the server that are invisible and in addition to this, if the status service dies then the entire front page would die. 

cc @IceeMC

**Comment by anishanne** [comment]
Make it so that a system updates a bots status in the DB every x minutes.

If statuses go down, whatever the bots most recently stored status in the DB was would stay, your home page would still exist.

**Comment by advaith1** [comment]
We currently update the status on the presence update event, which is what we should keep doing

I don't see why the homepage would die if the status service dies though?

**Comment by anishanne** [comment]
Only thing that would happen is offline bots would still show as offline even if they come online.
But that's a small price to pay.

**Comment by Cairo2k18** [comment]
> We currently update the status on the presence update event, which is what we should keep doing
> 
> I don't see why the homepage would die if the status service dies though?

I'm saying if discord starts having issues it would break the entire front page

**Comment by anishanne** [comment]
How?

Discord has issues, system won't update the bot's status. But online bots statuses will still be stored as online. All that will break is updating bots statuses.

**Comment by IceeMC** [comment]
Personally, I do not like this idea. It's a bit biased and can throw off results.

**Comment by anishanne** [comment]
How is not displaying offline bots biased?
Offline = people inviting bot have to wait before using

**Comment by IceeMC** [comment]
Yeah, but it skews results of featured random bots.

**Comment by anishanne** [comment]
> Yeah, but it skews results of featured random bots.

If your bot is offline it doesn't deserve to be featured. It gives a negative reputation if you have someone invite a bot only to realize its offline.

**Comment by IceeMC** [comment]
So, It's still a bit biased.

**Comment by anishanne** [comment]
Your unwilling to be biased against offline bots/bots that don't function?

**Comment by Cairo2k18** [comment]
> How?
> 
> Discord has issues, system won't update the bot's status. But online bots statuses will still be stored as online. All that will break is updating bots statuses.

But when the site tries to fetch it's status it will make them all offline.

**Comment by IceeMC** [comment]
Yes, because this list is unbiased, and adding a small thing that makes it a tiny bit biased is a TERRIBLE idea.

**Comment by advaith1** [comment]
IMO it isn't ok to show offline bots

**Comment by IceeMC** [comment]
Well, fuck your opinion

**Comment by IceeMC** [comment]
> IMO it isn't ok to show offline bots

To be fair Cairo is also against this.

**Comment by anishanne** [comment]
Ok so don't deny bots. That's biased. Even bots that have no commands, otherwise you're being biased bro.

> To be fair Cairo is also against this.
He doesn't wanna break the home page, afaik he has nothing against the concept

**Comment by advaith1** [comment]
calling only showing bots that work "biased" is seriously stretching the definition

**Comment by DuckMasterAl** [comment]
@everyone (if only that worked) we could just put a little icon next to the bot stating it’s offline and may not work when it’s on the homepage.
@anishanne @IceeMC @advaith1 pings for days

**Comment by advaith1** [comment]
and if discord breaks then the bots won't work anyway soo....

**Comment by anishanne** [comment]
> and if discord breaks then the bots won't work anyway soo....

If discord breaks, ALL THAT WILL HAPPEN is offline bots stay as offline and online bots stay as online. That is it.

>  we could just put a little icon next to the bot stating it’s offline and may not work when it’s on the homepage.

hey user, we know you came here to view some bots. Here are 12, but 2 of them don't work, but we'll still show them to you cause we are truly unbiased!

**Comment by Cairo2k18** [comment]
I feel like in some ways this would be useful, but at the same time if you really want to implement it we would have to spend time considering how to implement this. 

In addition to this, if we do implement this we should implement various other ways to monitor all bot's statuses to ensure that we are not listing "dead" bots.

> @everyone (if only that worked) we could just put a little icon next to the bot stating it’s offline and may not work when it’s on the homepage.
> @anishanne @IceeMC @advaith1 pings for days

You didn't need to mention us lol



> and if discord breaks then the bots won't work anyway soo....

I mean couldn't just part of the API die and the other half be fine though? I don't know so /shrug

**Comment by DuckMasterAl** [comment]
What if they’re invisible @anishanne

**Comment by DuckMasterAl** [comment]
> and if discord breaks then the bots won't work anyway soo....

I mean if you wanna be real fancy have a check for that so if all bots are offline then just **f**

**Comment by IceeMC** [comment]
> What if they’re invisible @anishanne

You don't know if they're invisible or not, therefore in my opinion that skews a tiny bit of results.

**Comment by Cairo2k18** [comment]
> If discord breaks, ALL THAT WILL HAPPEN is offline bots stay as offline and online bots stay as online. That is it.

How? All statuses are refreshed every x minutes and also, what if the site is restarted, etc, etc..?

**Comment by anishanne** [comment]
What bot that wants to be used shows itself as invisible. That's plain stupid and idioticy.

> How? All statuses are refreshed every x minutes and also, what if the site is restarted, etc, etc..?

According to advaith it uses the on_presence_change event. so...

**Comment by IceeMC** [comment]
> What bot that wants to be used shows itself as invisible. That's plain stupid and idioticy.
> 
> > How? All statuses are refreshed every x minutes and also, what if the site is restarted, etc, etc..?
> 
> According to advaith it uses the on_presence_change event. so...

LMAO NO WE DO NOT, we use presenceUpdate emitted by discord.js

**Comment by advaith1** [comment]
no public bots are invisible (other than the patreon integration which isn't really a bot); if a user sees a bot is offline then they'll probably just kick it anyway

if discord is saying that a bot is offline then the bot will probably actually not work

**Comment by advaith1** [comment]
@IceeMC presence updates are emitted by discord...

**Comment by anishanne** [comment]
> LMAO NO WE DO NOT, we use presenceUpdate emitted by discord.js

Same thing.

**Comment by IceeMC** [comment]
> @IceeMC presence updates are emitted by discord...

Do I look retarded?

**Comment by Cairo2k18** [comment]
> What bot that wants to be used shows itself as invisible. That's plain stupid and idioticy.

I agree to be fair but there are still bots that do this /shrug

> > How? All statuses are refreshed every x minutes and also, what if the site is restarted, etc, etc..?
> 
> According to advaith it uses the on_presence_change event. so...

We do update every time a presence is emitted, HOWEVER in conjuction with that we still have it update every x minutes, I could change that however.

**Comment by anishanne** [comment]
> We do update every time a presence is emitted, HOWEVER in conjuction with that we still have it update every x minutes, I could change that however.

Then change it lol, can't be that hard.

**Comment by anishanne** [comment]
The goal is to show users bots that they can use, not bots that exist but may or may not be useable.

**Comment by DuckMasterAl** [comment]
> > @IceeMC presence updates are emitted by discord...
> 
> 
> 
> Do I look retarded?

Was this a rhetorical question or...
||The answer is no... at least not yet. But you GitHub bio is||

**Comment by advaith1** [comment]
checking every x minutes isn't really needed

**Comment by Cairo2k18** [comment]
> checking every x minutes isn't really needed

Fair

**Comment by IceeMC** [comment]
> > checking every x minutes isn't really needed
> 
> Fair

Well, it's quicker than updating it.

**Comment by advaith1** [comment]
what?

**Comment by Cairo2k18** [comment]
> We do update every time a presence is emitted, HOWEVER in conjuction with that we still have it update every x minutes, I could change that however.

Turns out is isn't, I thought it was.

**Comment by IceeMC** [comment]
> > > @IceeMC presence updates are emitted by discord...
> > 
> > 
> > Do I look retarded?
> 
> Was this a rhetorical question or...
> 
> The answer is no... at least not yet. But you GitHub bio is

Oh fuck off will you

**Comment by anishanne** [comment]
Whats the verdict lol

**Comment by Cairo2k18** [comment]
> Whats the verdict lol

Might hold a vote on the server

**Comment by IceeMC** [comment]
> > Whats the verdict lol
> 
> Might hold a vote on the server

honestly the best solution here

**Comment by anishanne** [comment]
Thonk.

**Comment by anishanne** [comment]
Why would you lock it to collaborators? Ice is a collaborator and he's going at it.

**Comment by advaith1** [comment]
thats what i said in the server lol and why i unlocked it

but can we stop

**Comment by DuckMasterAl** [comment]
Personally, I still feel like we should make it so that they’re still on the homepage but with a little note/warning but it doesn’t really matter. As long as we either don’t have them or know that they’re offline. It would just be better since otherwise the list would be a little biased.

**Comment by advaith1** [comment]
added in dev (v5.1)
