### ISSUE TITLE
Auto Profile Sign in when Logging Out

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#46]
**Describe the Bug**

When logging out on the profile menu, it auto logs you back in.
**Steps to Reproduce**

1. Log out on your profile
**Expected Behavior**

It takes you to the home page.
**Screenshots**

I have a video if you want to watch it. [Quality Video of Buggo :bug:](https://youtu.be/NpToHdiFNo4)
**Environment**

- OS: MacOS Catalina 10.15.4
- Browser: Chrome
- Version: 83.0.4103.116 (64-bit)

**Comment by Cairo2k18** [comment]
This is because it redirects you back to the same page, which as `@me` in it. Which (if you're logged out) kinda doesn't work well. 
Looks like i'm going to have to add a bunch of checks for pages now.... F
