### ISSUE TITLE
Issue with the profile

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [discordextremelist/website#50]
Issue: 
For the "github" profile link it shows "gitlab" instead of the github one. 
https://github.com/discordextremelist/website/blob/29cdc5a70305b836c749dbc08e980c985ea22db9/assets/Views/templates/users/profile.ejs#L234

Simple Fix:
```ejs
href: `https://github.com/${userProfile.profile.links.github}`, 
```

**Comment by Cairo2k18** [comment]
Fixed, thanks!
