### ISSUE TITLE
Add "Sync" button for servers.

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [discordextremelist/website#51]
**Describe the solution you'd like**
Add an "Update Only" or "Sync" button to the /servers list.. to update the server icon/name so it updates the information without sending 
"USER-NAME (USER-ID) edited server NAME (ID) https://discordextremelist.xyz/servers/ID"
to the Discord server. 

**Describe alternatives you've considered**
It's possible by just clicking on 'submit' but it would be better for everyone to just add an "Sync" button.

**Comment by advaith1** [comment]
Planned, but I'm not sure if we should let all users do it or only the listing owner

**Comment by Cairo2k18** [comment]
> Planned, but I'm not sure if we should let all users do it or only the listing owner


imo only listing owners and mods+

**Comment by advaith1** [comment]
added in dev (v5.1)
