### ISSUE TITLE
Be able to play snake with WASD

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#57]
**Is your feature request related to a problem? Please describe.**
Yes, It's annoying to play snake with the arrow keys.
**Describe the solution you'd like**
Be able to play the snake game with WASD.

**Comment by Cairo2k18** [comment]
mr snake only likes arrow keys though :(

**Comment by Cairo2k18** [comment]
poor mr snake

**Comment by DuckMasterAl** [comment]
> mr snake only likes arrow keys though :(

Well it makes it a lot harder for mr snake to get food 😐

**Comment by Cairo2k18** [comment]
> > mr snake only likes arrow keys though :(
> 
> Well it makes it a lot harder for mr snake to get food 😐

dw I did add it

**Comment by DuckMasterAl** [comment]
Yea, I know :p

**Comment by Cairo2k18** [comment]
> comes out tomorrow
not necessarily, ideally later today

**Comment by DuckMasterAl** [comment]
> > comes out tomorrow
> 
> not necessarily, ideally later today

Not for me lol _unless it comes out in the next 57 minutes..._
