### ISSUE TITLE
Server edit bug

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [discordextremelist/website#66]
**Describe the Bug**
Shows ![img](https://i.imgur.com/2BMMDxe.png) when you edit a server.

**Steps to Reproduce**
Go to `https://discordextremelist.xyz/en-US/servers/YOUR_SERVER_ID/edit` and you should see it. 

**Expected Behavior**
To not show that part? lmao

**Environment**
- OS: Windows 10
- Browser: Opera
- Version: 68.0.3618.197 (64 Bit)

**Comment by advaith1** [comment]
probably got pasted in the wrong file lmao
