### ISSUE TITLE
Add a link to the snake score

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#67]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Make it so that when you click on the snake score on someone's profile it redirects you to the snake leaderboard.

**Comment by Cairo2k18** [comment]
Why? They won't necessarily be on the leaderboard.

**Comment by DuckMasterAl** [comment]
> Why? They won't necessarily be on the leaderboard.

So you can see other people's scores and stuff. It makes sense since it has something to do with the Snake Scores.

**Comment by Cairo2k18** [comment]
#149
