### ISSUE TITLE
@Cairo2k18 just an idea maybe move the logout button to the bottom, instead of the leaderboard at the bottom.

### ISSUE THREAD

**Issue by Cairo2k18** [discordextremelist/website#71]
@Cairo2k18 just an idea maybe move the logout button to the bottom, instead of the leaderboard at the bottom.
<img width="257" alt="Screen Shot 2020-07-16 at 9 36 22 AM" src="https://user-images.githubusercontent.com/43557963/87677654-05f90500-c748-11ea-8822-ae70d83c0f98.png">

_Originally posted by @DuckMasterAl in https://github.com/discordextremelist/website/issues/27#issuecomment-659417855_

**Comment by DuckMasterAl** [comment]
🏓 Pong
