### ISSUE TITLE
Syncing Servers as Staff

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#73]
**Describe the Bug**

Sync a server as staff and you get a 403 no perms error.
**Steps to Reproduce**

1. Go to [a server on del](https://discordextremelist.xyz/en-US/servers/568567800910839811)
2. Sync the server in the staff management option
3. Play the snake game on the 403 error page

**Expected Behavior**

It syncs the server

**Environment**

- OS: Mac OS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 83.0.4103.116 (64-bit)
  

**Additional Information**
This does not happen with templates, and bots don't have the sync button.

**Comment by Cairo2k18** [comment]
Mods should be able to sync all listings, not edit them though.

**Comment by advaith1** [comment]
fixed in dev

**Comment by Cairo2k18** [comment]
Nice
