### ISSUE TITLE
Page scrolling on bottom of page

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#74]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Add a page scroll button to the bottom of pages.
**Describe alternatives you've considered**
A back to top button to go to the top scroll button
**Additional context**
This is what I mean by scroll button 
<img width="1363" alt="Screen Shot 2020-07-23 at 11 20 05 PM" src="https://user-images.githubusercontent.com/43557963/88357945-13f7e880-cd3b-11ea-9a7b-b3ae77267b7f.png">

**Comment by advaith1** [comment]
ig we should move this to a partial because duplicating all the code is a bad idea

**Comment by Cairo2k18** [comment]
This is already implemented on some pages iirc

**Comment by advaith1** [comment]
at the bottom? i only see it at the top

**Comment by Cairo2k18** [comment]
> some 

Misworded that, I believe it has it at the bottom on only the audit page.
