### ISSUE TITLE
Bots not kicked on decline

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#77]
Auto-kick bots that have been approved/denied from the testing server.

**Comment by TheMoksej** [comment]
Aren't approved bots being kicked automatically?

**Comment by advaith1** [comment]
i don't think so

**Comment by advaith1** [comment]
oh hm, looks like it does, sometimes at least

maybe theres a bug with it?

**Comment by TheMoksej** [comment]
I believe I reported that quite some time ago, but that wasn't kicking declined bots, only approved.

**Comment by Cairo2k18** [comment]
Looks like it only does it on approve, not decline.

**Comment by advaith1** [comment]
Fixed by 2ece788c38157c07981c16bfc237a0c43ee2fe71
