### ISSUE TITLE
The snake leaderboard is not centered

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#79]
**Describe the Bug**

The snake leaderboard is not centered
**Steps to Reproduce**

1. Go to the snake leaderboard page

**Expected Behavior**

The leaderboard is centered

**Screenshots**

<img width="1435" alt="Screen Shot 2020-07-26 at 9 30 37 PM" src="https://user-images.githubusercontent.com/43557963/88495336-9d035f80-cf87-11ea-9045-9f00642ba074.png">

**Environment**

- OS: Mac OS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 83.0.4103.116 (64-bit)

**Additional context**

If this is not a bug, make it a feature request, it looks bad and is hard to read.

**Comment by Cairo2k18** [comment]
NAB

**Comment by Cairo2k18** [comment]
I'm planning on redoing the leaderboard in the future.

**Comment by DuckMasterAl** [comment]
> NAB

If this is not a bug, make it a feature request, it looks bad and is hard to read.

**Comment by Cairo2k18** [comment]
> > NAB
> 
> If this is not a bug, make it a feature request, it looks bad and is hard to read.



> I'm planning on redoing the leaderboard in the future.

**Comment by DuckMasterAl** [comment]
Ok :/
