### ISSUE TITLE
Everyone can sync anyone's entry to the site

### ISSUE THREAD

**Issue by angeloanan** [discordextremelist/website#81]
**Describe the Bug**
Anyone (even unauthenticated user) can use the `sync` feature. This can be abused and cause slowdowns to the Database.

**Steps to Reproduce**
1. Navigate to an entry (Users, Bots, Server)
2. Add a `/sync` to the URL

**Expected Behavior**
HTTP 403 or something else

**Additional context**
Problem caused because `permission.auth` or `permission.member` isn't even checked on hitting that endpoint. [See the faulty code here](https://github.com/discordextremelist/website/blob/528de3d08d1d0390223b4c5fa8da0b92325ce1a1/src/Routes/users.ts#L503)

**Comment by advaith1** [comment]
Intentional, there is no security issue with this
