### ISSUE TITLE
Some user permissions in the Database can be null

### ISSUE THREAD

**Issue by angeloanan** [discordextremelist/website#82]
**Describe the Bug**
User permissions in database can be null randomly. This causes a permission elevation vulnerability that allows people to edit anyone's entry to the DB.

Specific Permission: `Users#rank.assistant`.

The cause of this is still unknown and we (me and @IceeMC) are still figuring it out.

**Additional context**
[Chatlog in #testers at DEL's Discord](https://discordapp.com/channels/568567800910839811/694794551310811186/737414911294177432)

**Comment by Cairo2k18** [comment]
Disclose security vulnerabilities properly next time.
