### ISSUE TITLE
Inputting the opposite + other way at the same time in Snake game sometime kills the game

### ISSUE THREAD

**Issue by angeloanan** [discordextremelist/website#83]
**Steps to Reproduce**
* Go to snek game
* Notice how the snek is moving:
  * If it's moving left, try inputting **Right + Up** or **Right + Down** at the same time
  * If it's moving right, try inputting **Left + Up** or **Left + Down** at the same time

**Expected Behavior**
The snek turns / ignores one of the input

**Video**
[yes](https://cdn.discordapp.com/attachments/721594899518062603/737447067701739560/2020-07-28_05-15-59.mp4)

**Environment**
- OS: Windows 10
- Browser: MS Edge (Chromium) 84.0.522.44 (Official build)

**Comment by Cairo2k18** [comment]
Too minor.

**Comment by TheMoksej** [comment]
bruh
