### ISSUE TITLE
Delly shows in search results

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#87]
**Describe the Bug**

The internal bot "Delly" shows up in search results even though it's not supposed to.
**Steps to Reproduce**

1. Go to the search page
2. Search for Delly

**Expected Behavior**

No results are found

**Screenshots**

<img width="1440" alt="Screen Shot 2020-07-28 at 12 54 46 PM" src="https://user-images.githubusercontent.com/43557963/88697140-2161f980-d0d2-11ea-83b1-a5ca302fc3af.png">

**Environment**

- OS: Mac OS Catalina 10.15.6 (19G73)
- Browser: Chrome
- Version: 83.0.4103.116 (64-bit)

**Additional Information**
There are also 2 periods instead of 1

**Comment by Cairo2k18** [comment]
Should've been three.
