### ISSUE TITLE
Navbar dropdowns don't work on mobile

### ISSUE THREAD

**Issue by Arthur-Systems** [discordextremelist/website#88]
**Describe the Bug**
Using a desktop grade browser or requesting the "desktop site" on mobile with a screen size less than 1023 px will but bigger than 769 px will cause the the "More" and "Translate" menu to fully open but they will not be able to close. Any screens less than 769 px will cause the two menus too close. In this state the user is still not able to interact with it so it is impossible to access the menu contents. Resizing the browser will also cause the same effect. This causes Muti tasking to be impossible with devices with smaller screens. 

**Environment**

- OS: TESTED ON MAC OS (10.15.6 ) AND WINDOWS 10 

- Browser: Chrome, Firefox, Opera, Edge

  

**Additional context**
<h6> :3 lol </h6>

**Comment by Cairo2k18** [comment]
The mobile desktop site thing is NAB, we don't support that. I'll look into the other one though regarding desktop resizing.

**Comment by advaith1** [comment]
this now affects all phones so its high priority

**Comment by Cairo2k18** [comment]
Login button is also hidden
